name: Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allow to run this workflow manually
  workflow_dispatch:

env:
  SLACK_CHANNEL_ID: C0471B2N86L

jobs:
  style-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Setup Node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
        with:
          node-version: "24.11.1"
          cache: npm
          cache-dependency-path: ./package-lock.json
      - name: Cache node_modules
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7
        id: node-modules-cache
        with:
          path: |
            ./node_modules
          key: modules-${{ hashFiles('./package-lock.json') }}
      - name: Cache style checks
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7
        id: style-check-cache
        with:
          path: .cache
          key: style-check-${{ github.ref }}-${{ github.sha }}
          # If no direct cache hit for the current commit, fallback to the latest cache
          restore-keys: |
            style-check-${{ github.ref }}-
            style-check-
      - name: Install dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: |
          npm ci --ignore-scripts
      - name: Check format
        run: npm run format:check
      - name: Send status to Slack
        uses: digitalservicebund/notify-on-failure-gha@671832f192aee0a068fd92b2f6deb975df794a84 # v1.6.1
        if: ${{ failure() && github.ref == 'refs/heads/main' }}
        with:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: ${{ env.SLACK_CHANNEL_ID }}

  validate-xsd-schema-samples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Install xmllint
        run: |
          sudo apt-get update
          sudo apt-get install libxml2-utils -y
      - name: Check caselaw samples against schema
        run: xmllint --noout --schema xsd/caselaw.xsd samples/caselaw/*.xml
      - name: Send status to Slack
        uses: digitalservicebund/notify-on-failure-gha@671832f192aee0a068fd92b2f6deb975df794a84 # v1.6.1
        if: ${{ failure() && github.ref == 'refs/heads/main' }}
        with:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: ${{ env.SLACK_CHANNEL_ID }}
