name: publish-reports.yml
on:
  workflow_call:
    secrets:
      REPORTS_BUCKET_ACCESS_KEY_ID:
        required: true
      REPORTS_BUCKET_SECRET_ACCESS_KEY:
        required: true

jobs:
  adrs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout ris-xml-schema repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          path: ris-xml-schema
      - name: Add to report
        uses: digitalservicebund/add-ris-report@31a248ea368f94bfa3a012da3c202bcc6be2debe
        with:
          filePath: ris-xml-schema/adr
          destinationDir: adr/ris-xml-schema
          reportIsDirectory: true
          keepAllVersions: false
          BUCKET_ACCESS_KEY_ID: ${{ secrets.REPORTS_BUCKET_ACCESS_KEY_ID }}
          BUCKET_SECRET_ACCESS_KEY: ${{ secrets.REPORTS_BUCKET_SECRET_ACCESS_KEY }}
