name: publish-reports.yml
on:
  workflow_call:
    secrets:
      REPORTS_BUCKET_ACCESS_KEY_ID:
        required: true
      REPORTS_BUCKET_SECRET_ACCESS_KEY:
        required: true

jobs:
  adrs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout ris-xml-schema repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          path: ris-xml-schema
      - name: Add to report
        uses: digitalservicebund/add-ris-report@5980f8dc97ec0aea58656e79e391eea59a9dfea8
        with:
          filePath: ris-xml-schema/adr
          destinationDir: adr/ris-xml-schema
          reportIsDirectory: true
          keepAllVersions: false
          BUCKET_ACCESS_KEY_ID: ${{ secrets.REPORTS_BUCKET_ACCESS_KEY_ID }}
          BUCKET_SECRET_ACCESS_KEY: ${{ secrets.REPORTS_BUCKET_SECRET_ACCESS_KEY }}
